---
- name: Add systemd service
  tags:
    - upstart
  template: src=template.service.j2 dest=/etc/systemd/system/{{ service_name }}.service
  register: systemd_unit_file
  sudo: yes

- name: Reload service file
  command: /bin/systemctl daemon-reload
  when: systemd_unit_file.changed
  sudo: yes

- name: Enable and possibly restart service
  tags:
    - upstart
  service: name={{ service_name }} enabled=yes state={{ "restarted" if service_restart else omit }}
  sudo: yes
